FROM node:21-alpine3.18 AS stageOne
WORKDIR /build
COPY ./core .
RUN npm install 
RUN npm run build

FROM node:21-alpine3.18 AS stageTwo
WORKDIR /build
WORKDIR /core
COPY --from=stageOne /build/ .
RUN cd ..
WORKDIR /user/confirmation-email
COPY ./user/confirmation-email/ .
RUN npm install
RUN npm run build

FROM node:21-alpine3.18 AS production
WORKDIR /app
COPY --from=stageTwo /user/confirmation-email/dist .
EXPOSE 6002
CMD ["node", "./main.js"]