FROM node:21-alpine3.18 AS stageOne
WORKDIR /build
COPY ./core .
RUN npm install 
RUN npm run build

FROM node:21-alpine3.18 AS stageTwo
WORKDIR /build
WORKDIR /core
COPY --from=stageOne /build/ .
RUN cd ..
WORKDIR /client/document
COPY ./client/Document/ .
RUN npm install
RUN npm run build

FROM node:21-alpine3.18 AS production
WORKDIR /app
COPY --from=stageTwo /client/document/dist .
EXPOSE 9002
CMD ["node", "./main.js"]