FROM node:21-alpine3.18 AS stageOne
WORKDIR /build
COPY ./core .
RUN npm install 
RUN npm run build

FROM node:21-alpine3.18 AS stageTwo
WORKDIR /build
WORKDIR /core
COPY --from=stageOne /build/ .
RUN cd ..
WORKDIR /user/auth
COPY ./user/auth/ .
RUN npm install
RUN npm run build

FROM node:21-alpine3.18 AS production
WORKDIR /app
COPY --from=stageTwo /user/auth/dist .
EXPOSE 6000
CMD ["node", "./main.js"]