global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['opentelemetry-collector:8889']
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']