server:
  port: 8081
  compression:
    enabled: true
    mime-type: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  rabbitmq:
    host: ${rabbitMQ.rabbitMQ_host}
    port: ${rabbitMQ.rabbitMQ_port}
    username: ${rabbitMQ.rabbitMQ_user}
    password: ${rabbitMQ.rabbitMQ_password}
    queue: ${rabbitMQ.rabbitMQ_queue}

mail:
  dispatcher:
    otlp:
      tracing-server: "http://opentelemetry-collector:4318/v1/traces"
  sender:
    host: ${mail_sender.host}
    port: ${mail_sender.port}
    username: ${mail_sender.username}
    password: ${mail_sender.password}
